openapi: "3.0.0"
info:
  title: Review App Api
  description: Review app is simple app. User can add product for review and then other user can review it. All user aninomous. No user identity.
  termOfService: http://reviewapp.tritechfirm.com/review-app-terms
  contact: 
    name: Ziauddin Robin
    email: info@tritechfirm.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  externalDocs:
    description: Find out more about 
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: './paths/pets.yml'
  /pets/{petId}:
    $ref: './paths/pet.yml'
components:
  schemas:
    Pet:
      $ref: './components/pet.yml'
    Pets:
      $ref: './components/pets.yml'
    Error:
      $ref: './components/error.yml'
